name: Build

on:
  workflow_dispatch:

env:
  AWS_REGION: 'us-east-1'
  BKT_ARG: 'dev-lambda-alias mm-808-dev-terraform-files'

permissions:
  id-token: write # this is needed to use OIDC token
  contents: read
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python script
        run: |
          cd py_code
          python echo_items.py
