name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.workflow_info.outputs.repo_name }}
      repo_branch: ${{ steps.workflow_info.outputs.repo_branch }}
      vers: ${{ steps.workflow_info.outputs.vers }}
      env_name: ${{ steps.workflow_info.outputs.env_name }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Python script
        run: |
          set -eu
          cd py_code
          python echo_items.py

      - name: Get workflow info
        id: workflow_info
        run: |
          set -eu

          RUN_ID=${GITHUB_RUN_ID:0:3}
          echo "${RUN_ID}"

          REPO_NAME=${GITHUB_REPOSITORY}
          REPO_BRANCH="$(echo $GITHUB_REF | cut -d'/' -f3)"
          VERS="$(GITHUB_RUN_NUMBER.$RUN_ID)"
          ENV_NAME="$(echo $GITHUB_REF | cut -d'/' -f3)" # same as branch because I don't have environments in non Enterprise account
          JOB_STATUS=${{ job.status }}

          #just checking, remove after working correctly
          echo "repo_name ${REPO_NAME}"
          echo "repo_branch ${REPO_BRANCH}"
          echo "vers ${VERS}"
          echo "env_name ${ENV_NAME}"
          echo "job_status ${JOB_STATUS}"

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${REPO_NAME}/actions/workflows/edit_badges.yml/dispatches \
          -d '{"ref":"dev", \
            "inputs": { \
            "repo_name": "${REPO_NAME}",
            "repo_branch": "${REPO_BRANCH}",
            "vers": "${VERS}",
            "env_name": "${ENV_NAME}",
            "job_status": "${JOB_STATUS}", \
            }}'

  # edit-badges:
  #   needs: run-script
  #   uses: mm808/update_readme_badges/.github/workflows/edit_badges.yml@dev
  #   with:
  #     repo_name: ${{needs.run-script.outputs.repo_name}}
  #     repo_branch: ${{needs.run-script.outputs.repo_branch}}
  #     vers: ${{needs.run-script.outputs.vers}}
  #     env_name: ${{needs.run-script.outputs.env_name}}
