name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    outputs: 
      repo_name: ${{ steps.workflow_info.outputs.repo_name }}
      repo_branch: ${{ steps.workflow_info.outputs.repo_branch }}
      vers: ${{ steps.workflow_info.outputs.vers }}
      env_name: ${{ steps.workflow_info.outputs.env_name }}
      
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # - name: Run Python script
      #   run: |
      #     cd py_code
      #     python echo_items.py

      - name: Get workflow info
        id: workflow_info
        run: |          
          echo "repo_name=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_OUTPUT
          echo "repo_branch=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT
          echo "vers=$GITHUB_RUN_NUMBER.$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
          echo "env_name=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT # same as branch because I don't have environments
  
  # echo-outputs:
  #   needs: run-script
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: debug outputs
  #       run: |
  #         echo "Repo Name ${{needs.run-script.outputs.repo_name}}"
  #         echo "E Name ${{needs.run-script.outputs.env_name}}"

  edit-badges:
    needs: run-script
    uses: mm808/update_readme_badges/.github/workflows/edit_badges.yml@dev
    with:
      repo_name: ${{needs.run-script.outputs.repo_name}}
      repo_branch: ${{needs.run-script.outputs.repo_branch}}
      vers: ${{needs.run-script.outputs.vers}}
      env_name: ${{needs.run-script.outputs.env_name}}
    # secrets:
    #   PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
