name: Edit badges

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        env_name:
          type: string
          required: true
        vers:
          type: string
          required: true
        
permissions:
  contents: read

jobs:
  Edit_Badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get workflow info
        run: |
          echo "run_num=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "run_id=$GITHUB_RUN_ID" >> $ GITHUB_ENV

      - name: edit badges