name: Edit badges

on:
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        required: true
      vers:
        type: string
        required: true

  workflow_call:
    inputs:
      env_name:
        type: string
        required: true
      vers:
        type: string
        required: true

permissions:
  contents: read

jobs:
  Edit_Badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: construct new version
        run: |
          echo ${{ inputs.vers }}
          echo ${{ inputs.env_name }}
